"""Data-quality cleaning — rule-based, leakage-safe correction of impossible values.

Only *domain-impossible* values are touched (a 0 FICO, a negative or 2013-month tenure). These are
deterministic rules, not distribution-based, so applying them before the train/test split does NOT
leak information (unlike winsorisation or imputation, which stay inside the CV folds).

This module is ADDITIVE. It does not change the modelling path until `clean()` is explicitly wired
into the pipeline (a separate decision, pending sign-off). Use:
  * `python -m emerald_ai clean-report`  -> reports/data_quality.md (impact, no model change)
"""
from __future__ import annotations

import numpy as np
import pandas as pd

from . import config as C
from . import data as D


def detect_issues(df: pd.DataFrame) -> list[dict]:
    """Return per-rule counts of domain-impossible values (no mutation)."""
    return [
        {"rule": f"Credit Score < {C.CREDIT_SCORE_FLOOR} (impossible FICO; missing-coded)",
         "column": C.CREDIT_SCORE_COL,
         "n_affected": int((df[C.CREDIT_SCORE_COL] < C.CREDIT_SCORE_FLOOR).sum())},
        {"rule": f"Time In Business < {C.TIB_MIN_MONTHS} (negative tenure)",
         "column": C.TIB_COL,
         "n_affected": int((df[C.TIB_COL] < C.TIB_MIN_MONTHS).sum())},
        {"rule": f"Time In Business > {C.TIB_MAX_MONTHS} months (>50yr; likely year typo)",
         "column": C.TIB_COL,
         "n_affected": int((df[C.TIB_COL] > C.TIB_MAX_MONTHS).sum())},
    ]


def clean(df: pd.DataFrame) -> tuple[pd.DataFrame, list[dict]]:
    """Return (cleaned copy, change log). Impossible values -> NaN, left for fold-wise imputation."""
    out = df.copy()
    log = detect_issues(df)
    out.loc[out[C.CREDIT_SCORE_COL] < C.CREDIT_SCORE_FLOOR, C.CREDIT_SCORE_COL] = np.nan
    out.loc[out[C.TIB_COL] < C.TIB_MIN_MONTHS, C.TIB_COL] = np.nan
    out.loc[out[C.TIB_COL] > C.TIB_MAX_MONTHS, C.TIB_COL] = np.nan
    return out, log


def build_report() -> str:
    """Write reports/data_quality.md describing what cleaning would change (no model change)."""
    from .eda import _md_table

    C.ensure_dirs()
    df = D.load_raw()
    issues = detect_issues(df)
    total = sum(i["n_affected"] for i in issues)

    md = f"""# Data-Quality Report (rule-based cleaning)

*Generated by `python -m emerald_ai clean-report`. Rules are domain-impossible-value corrections —
deterministic and leakage-safe, so they may run before the train/test split. Distribution-based
treatment (winsorisation, imputation) stays INSIDE the CV folds and is not done here.*

## Impossible values detected
{_md_table(pd.DataFrame(issues))}

**Total cells corrected → NaN: {total}** of {len(df):,} rows ({100*total/len(df):.2f}% of the data).
These are set to missing and handled by the existing fold-wise median imputation; they are not
dropped, so the event count (50) is unchanged.

## Why this matters
- A `Credit Score` of 0 is not a real FICO; left as-is it corrupts the one feature lenders trust
  most. The Rule-2 audit found `Credit Score` alone scored *below* the dummy floor — this coding is
  a prime suspect.
- A `Time In Business` of 2013 months (≈168 years) is a data-entry artefact (a year in a months
  field); it distorts scaling and any tree split on tenure.

## Status
Cleaning is **not yet wired into the modelling pipeline** — this report only shows the impact.
Integrating `clean()` into the data path and re-running the bake-off + evidence is the next step,
pending sign-off (it changes model inputs).

---
*Reproduce: `python -m emerald_ai clean-report`*
"""
    out = C.REPORTS_DIR / "data_quality.md"
    out.write_text(md, encoding="utf-8")
    return str(out)
