"""Survival-analysis feasibility check — can the censored `current` loans be used via time-to-event?

The idea behind option (a): the primary label (`paidoff_only`) DROPS the ~10k right-censored
`current` loans, discarding information. A time-to-default (survival) model could in principle use
them — a loan that has been `current` for 18 months without defaulting is informative.

A survival model needs a trustworthy clock per loan: time observed before the event (default) or
before censoring. This module asks, BEFORE fitting anything, whether such a clock exists in the
data. It does not — the two candidate durations disagree and are internally implausible — so a
proper survival analysis is **non-estimable** here. This module documents that with reproducible
evidence (mirroring the Phase-1 fairness non-estimability result), rather than fitting a Cox model
onto an incoherent time axis.

CITATION NOTE (Rule 1): the literature brain currently has **zero** survival/censoring/Cox papers —
a gap to close (Cox 1972; discrete-time survival, e.g. Tutz & Schmid) before any survival result
could ship. Run: ``python -m emerald_ai survival-check``.
"""
from __future__ import annotations

import numpy as np
import pandas as pd

from . import config as C
from . import data as D

# A paidOff loan that genuinely ran its course should sit near 100% term-complete; a 2015-2019
# origination observed at the ~2020 snapshot should show substantial elapsed term. We test both.
PAIDOFF_TERM_FLOOR = 90.0      # % term-complete we'd expect a true "paid off" loan to exceed
PLAUSIBLE_MIN_MONTHS = 1.0     # a loan lifetime under ~1 month is implausible as a survival time


def candidate_durations(df: pd.DataFrame) -> pd.DataFrame:
    """Build the two candidate survival clocks and summarise each by Deal Status."""
    d = df.copy()
    d["cal_months"] = (d["End"] - d["Start"]).dt.days / 30.44              # calendar (admin?) span
    d["term_months"] = d["Closed Max Term"] * d["Term Complete Percentage"] / 100  # term-based
    rows = []
    for st in ["default", "behind", "current", "paidOff"]:
        g = d[d[C.LABEL_COL] == st]
        rows.append({
            "status": st, "n": int(len(g)),
            "cal_months_median": round(float(g["cal_months"].median()), 2),
            "term_months_median": round(float(g["term_months"].median()), 2),
            "term_pct_median": round(float(g["Term Complete Percentage"].median()), 1),
        })
    return pd.DataFrame(rows), d


def coherence(d: pd.DataFrame) -> dict:
    """Quantify how incoherent the two clocks are, and the implausibility red flags."""
    both = d[["cal_months", "term_months"]].dropna()
    corr = float(np.corrcoef(both["cal_months"], both["term_months"])[0, 1]) if len(both) > 2 else np.nan
    paid = d[d[C.LABEL_COL] == "paidOff"]
    cur = d[d[C.LABEL_COL] == "current"]
    return {
        "clock_corr": corr,
        "paidoff_below_term_floor_pct": round(100 * float((paid["Term Complete Percentage"]
                                                            < PAIDOFF_TERM_FLOOR).mean()), 1),
        "current_cal_median_months": round(float(cur["cal_months"].median()), 2),
        "current_implausible_pct": round(100 * float((cur["cal_months"] < PLAUSIBLE_MIN_MONTHS).mean()), 1),
        "n_current_dropped": int(len(cur)),
    }


def build_report() -> str:
    from .eda import _md_table

    C.ensure_dirs()
    df = D.load_raw()
    table, d = candidate_durations(df)
    coh = coherence(d)

    estimable = (coh["clock_corr"] > 0.5 and coh["paidoff_below_term_floor_pct"] < 25
                 and coh["current_implausible_pct"] < 25)

    md = f"""# Survival-analysis feasibility — can the censored loans be used?

*Generated by `python -m emerald_ai survival-check`. Asks whether a trustworthy time-to-event clock
exists BEFORE fitting any survival model. Goal: recover the {coh['n_current_dropped']} right-censored
`current` loans that the `paidoff_only` label currently drops.*

## A survival model needs a reliable per-loan clock — does one exist?
Two candidate durations can be built from the data:
- **calendar** = `End − Start` (days/30.44);
- **term-based** = `Closed Max Term × Term Complete Percentage / 100`.

{_md_table(table)}

## They are incoherent — the clock is not trustworthy
- **Correlation between the two clocks = {coh['clock_corr']:.2f}** (a real duration would make them
  agree; they do not).
- **{coh['paidoff_below_term_floor_pct']}% of `paidOff` loans sit below {PAIDOFF_TERM_FLOOR:.0f}%
  term-complete** — a loan that genuinely "paid off" should be near 100%, so this column does not
  mean elapsed loan life.
- **`current` loans show a calendar span of only {coh['current_cal_median_months']} months
  (median)**, and {coh['current_implausible_pct']}% are under {PLAUSIBLE_MIN_MONTHS:.0f} month — implausibly
  short for 2015–2019 originations observed at a ~2020 snapshot. `End`/`Deal Closed` is evidently an
  administrative deal-booking date, not a maturity or default date.

## Verdict: {'ESTIMABLE' if estimable else 'NON-ESTIMABLE'}
{'A coherent clock exists; a survival model is worth fitting.' if estimable else
 '''**A proper survival analysis is NOT estimable on this dataset.** The exact rows we wanted to
exploit — the censored `current` loans — have untrustworthy observed-times, so a Cox / discrete-time
model would be built on a meaningless time axis. This is a documented non-estimability result (the
direct analogue of the Phase-1 fairness-audit finding), not a modelling choice to paper over.'''}

## What would unlock it (so what / next data)
A single reliable field would change the answer: a **default date** or **last-payment date** per
loan. With that, time-to-event and censoring time become well-defined and the {coh['n_current_dropped']}
censored loans could be recovered via discrete-time survival. Absent it, the defensible levers
remain: (1) a **cost-sensitive decision threshold** on the existing binary model; (2) **more events**
(longer observation window / pooled portfolio), per `reports/improvement.md`.

## Method → citation audit (Rule 1)
| Method | Status | Note |
|---|---|---|
| Survival / time-to-event modelling (Cox, discrete-time) | **GAP** | the literature brain has **zero** survival/censoring papers; would need Cox 1972 + a discrete-time survival reference before any survival result could ship |
| Documented non-estimability framing | **COVERED** | consistent with the Phase-1 fairness non-estimability result already in `reports/feasibility.md` |

---
*Reproduce: `python -m emerald_ai survival-check`*
"""
    out = C.REPORTS_DIR / "survival_feasibility.md"
    out.write_text(md, encoding="utf-8")
    return str(out)
